if(NOT IS_DIRECTORY "${ROOT}")
    message(FATAL_ERROR "VLC runtime directory does not exist: ${ROOT}")
endif()
file(MAKE_DIRECTORY "${DEST}")
file(GLOB libraries "${ROOT}/*.dll" "${ROOT}/libvlc*.so*" "${ROOT}/*.dylib")
foreach(library IN LISTS libraries)
    file(COPY "${library}" DESTINATION "${DEST}")
endforeach()
if(IS_DIRECTORY "${ROOT}/lib")
    file(COPY "${ROOT}/lib" DESTINATION "${DEST}")
endif()
if(IS_DIRECTORY "${ROOT}/plugins")
    file(COPY "${ROOT}/plugins" DESTINATION "${DEST}")
endif()
foreach(license COPYING COPYING.LIB)
    if(EXISTS "${ROOT}/${license}")
        file(COPY "${ROOT}/${license}" DESTINATION "${DEST}")
    elseif(EXISTS "${SOURCE_LICENSE_DIR}/${license}")
        file(COPY "${SOURCE_LICENSE_DIR}/${license}" DESTINATION "${DEST}")
    endif()
endforeach()
